# pyproject.toml
[tool.poetry]
name = "latched"
version = "0.0.0"
description = ""
authors = ["psycoder <psycoder@latched.ai>", "sungman <sungman@latched.ai>"]

[tool.poetry.dependencies]
python = "^3.11"
coremltools = "^7.2"


[tool.poetry.group.dev.dependencies]
